/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Utilidades.ModernTopMenu;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author gameV
 */
public class Administador extends javax.swing.JFrame {

    /**
     * Creates new form Administador
     */
    public Administador() {
        initComponents();
        añadirEmpleado.setUI(null); 

        ModernTopMenu menuSuperior = new ModernTopMenu(ModificarInfoAdmin);
        // 2️⃣ Crear el menú superior moderno
        menuSuperior = new Utilidades.ModernTopMenu(ModificarInfoAdmin);

        // 3️⃣ Aplicar colores personalizados
        menuSuperior.setColors(
                new Color(29, 35, 51), // Color principal del menú
                new Color(41, 50, 65), // Color hover
                Color.WHITE, // Texto blanco
                new Color(20, 25, 40), // Fondo principal oscuro
                new Color(24, 30, 45) // Fondo del desplegable
        );

        // 4️⃣ Establecer BorderLayout para que el menú quede arriba
        getContentPane().setLayout(new BorderLayout());

        // Buscar el panel principal que NetBeans generó (por ejemplo jPanel1)
        Component[] components = getContentPane().getComponents();
        JPanel mainPanel = null;

        for (Component comp : components) {
            if (comp instanceof JPanel && ((JPanel) comp).getComponentCount() > 0) {
                mainPanel = (JPanel) comp;
                break;
            }
        }

        // 5️⃣ Reorganizar los componentes
        if (mainPanel != null) {
            getContentPane().remove(mainPanel);
            getContentPane().add(menuSuperior, BorderLayout.NORTH);
            getContentPane().add(mainPanel, BorderLayout.CENTER);
        } else {
            getContentPane().add(menuSuperior, BorderLayout.NORTH);
        }

        // 6️⃣ Ajustar tamaño
        pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MotoEliminar = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        Despedir = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        modificar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        ModificarInfoAdmin = new javax.swing.JTabbedPane();
        añadirEmpleado = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Nombre1Field = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Nombre2Field = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        Apellido1Field = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        Apellido2Field = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        CorreoField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cedulaField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cedulaField1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cedulaField2 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        EliminarEmpleado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        ModificarEmpleado = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaModificación = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        VisualizarEmpleado = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        visualizarEmpleados = new javax.swing.JTable();
        AñadirMoto = new javax.swing.JPanel();
        VisualizarMoto2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboBoxTipoMoto2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        MarcaMotos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        EliminarMoto = new javax.swing.JPanel();
        tablaMotos = new javax.swing.JScrollPane();
        tablaDeCarrito = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        ModificarMoto = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        verInfo = new javax.swing.JPanel();
        VisualizarMoto1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboBoxTipoMoto1 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Nombre1Field1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Nombre2Field1 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        Apellido1Field1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        Apellido2Field1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        CorreoField1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        cedulaField3 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        cedulaField4 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        cedulaField5 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        MotoEliminar.setText("Eliminar esta moto");
        jPopupMenu1.add(MotoEliminar);

        Despedir.setText("DespedirEmpleado");
        jPopupMenu2.add(Despedir);

        modificar.setText("Modificar información");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPopupMenu3.add(modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModificarInfoAdmin.setBackground(new java.awt.Color(255, 255, 255));

        añadirEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        añadirEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-circle-34.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 40, 50));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Ingrese el primer nombre:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));

        Nombre1Field.setForeground(new java.awt.Color(0, 0, 0));
        Nombre1Field.setBorder(null);
        Nombre1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre1FieldActionPerformed(evt);
            }
        });
        jPanel3.add(Nombre1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 350, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 350, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese el segundo nombre:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-circle-34.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 40, 50));

        Nombre2Field.setForeground(new java.awt.Color(0, 0, 0));
        Nombre2Field.setBorder(null);
        Nombre2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre2FieldActionPerformed(evt);
            }
        });
        jPanel3.add(Nombre2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 350, 30));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 350, 20));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Ingrese el primer apellido:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 20));

        Apellido1Field.setForeground(new java.awt.Color(0, 0, 0));
        Apellido1Field.setBorder(null);
        Apellido1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido1FieldActionPerformed(evt);
            }
        });
        jPanel3.add(Apellido1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 350, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-circle-34.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 40, 50));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 350, 20));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Ingrese el segundo apellido:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 20));

        Apellido2Field.setForeground(new java.awt.Color(0, 0, 0));
        Apellido2Field.setBorder(null);
        Apellido2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido2FieldActionPerformed(evt);
            }
        });
        jPanel3.add(Apellido2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 350, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-circle-34.png"))); // NOI18N
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 40, 50));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 340, 20));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Ingrese el correo:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 20));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-email-34 (1).png"))); // NOI18N
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 40, 50));

        CorreoField.setForeground(new java.awt.Color(0, 0, 0));
        CorreoField.setBorder(null);
        CorreoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoFieldActionPerformed(evt);
            }
        });
        jPanel3.add(CorreoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 350, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 350, 20));

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Ingrese la cedula:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-id-42.png"))); // NOI18N
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 40, 50));

        cedulaField.setForeground(new java.awt.Color(0, 0, 0));
        cedulaField.setBorder(null);
        cedulaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaFieldActionPerformed(evt);
            }
        });
        jPanel3.add(cedulaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 350, 30));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 350, 20));

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Ingrese el número telefonico:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DEBE LLENAR TODOS LOS CAMPOS PARA PODER CONTRATAR UN NUEVO EMPLEADO");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-telephone-32.png"))); // NOI18N
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 40, 50));

        cedulaField1.setForeground(new java.awt.Color(0, 0, 0));
        cedulaField1.setBorder(null);
        cedulaField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaField1ActionPerformed(evt);
            }
        });
        jPanel3.add(cedulaField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 350, 30));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 350, 20));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingrese la edad:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 466, -1, 20));

        cedulaField2.setForeground(new java.awt.Color(0, 0, 0));
        cedulaField2.setBorder(null);
        cedulaField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaField2ActionPerformed(evt);
            }
        });
        jPanel3.add(cedulaField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 350, 30));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 350, 20));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-age-32.png"))); // NOI18N
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 40, 50));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unnamed-removebg-preview.png"))); // NOI18N
        jLabel28.setText("jLabel28");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 440, 350));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("VOLTRIX S.A.S COMPANY SOLO MANEJA CONTRATO A TERMINO INDEFINIDO, SEGÚN LA LEY 2395 DEL 2025");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 390, -1));

        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Entiendo y acepto los terminos y condiciones de contratación.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Contratar.");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 577, 120, 40));

        añadirEmpleado.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 660));

        ModificarInfoAdmin.addTab("tab10", añadirEmpleado);

        EliminarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        EliminarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Primer nombre", "Segundo nombre", "Primer apellido", "Segundo Apellido", "Edad", "Identificación", "Correo", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu2);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        EliminarEmpleado.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1120, 590));
        EliminarEmpleado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Seleccione el empleado que desea eliminar y dé click derecho para despedirlo. ");
        EliminarEmpleado.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 60));

        ModificarInfoAdmin.addTab("tab2", EliminarEmpleado);

        ModificarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaModificación.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Primer nombre", "Segundo nombre", "Primer apellido", "Segundo Apellido", "Edad", "Identificación", "Correo", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaModificación.setComponentPopupMenu(jPopupMenu3);
        jScrollPane2.setViewportView(tablaModificación);
        if (tablaModificación.getColumnModel().getColumnCount() > 0) {
            tablaModificación.getColumnModel().getColumn(0).setResizable(false);
            tablaModificación.getColumnModel().getColumn(1).setResizable(false);
            tablaModificación.getColumnModel().getColumn(2).setResizable(false);
            tablaModificación.getColumnModel().getColumn(3).setResizable(false);
            tablaModificación.getColumnModel().getColumn(4).setResizable(false);
            tablaModificación.getColumnModel().getColumn(5).setResizable(false);
            tablaModificación.getColumnModel().getColumn(6).setResizable(false);
            tablaModificación.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel12.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1120, 590));

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("PARA MODIFICAR UN EMPLEADO, HAGA CLICK DERECHO Y SE LE REDIGIDIRÁ A UNA NUEVA VENTANA.");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 30));

        ModificarEmpleado.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 660));

        ModificarInfoAdmin.addTab("tab3", ModificarEmpleado);

        VisualizarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visualizarEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Primer nombre", "Segundo nombre", "Primer apellido", "Segundo Apellido", "Edad", "Identificación", "Correo", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        visualizarEmpleados.setComponentPopupMenu(jPopupMenu3);
        jScrollPane3.setViewportView(visualizarEmpleados);
        if (visualizarEmpleados.getColumnModel().getColumnCount() > 0) {
            visualizarEmpleados.getColumnModel().getColumn(0).setResizable(false);
            visualizarEmpleados.getColumnModel().getColumn(1).setResizable(false);
            visualizarEmpleados.getColumnModel().getColumn(2).setResizable(false);
            visualizarEmpleados.getColumnModel().getColumn(3).setResizable(false);
            visualizarEmpleados.getColumnModel().getColumn(4).setResizable(false);
            visualizarEmpleados.getColumnModel().getColumn(5).setResizable(false);
            visualizarEmpleados.getColumnModel().getColumn(6).setResizable(false);
            visualizarEmpleados.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel16.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1120, 610));

        VisualizarEmpleado.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 660));

        ModificarInfoAdmin.addTab("tab4", VisualizarEmpleado);

        AñadirMoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VisualizarMoto2.setBackground(new java.awt.Color(255, 255, 255));
        VisualizarMoto2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("PARA AÑADIR UNA NUEVA MOTO INGRESE LOS DETALLES QUE SE LE PIDEN A CONTINUACIÓN:");
        VisualizarMoto2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 80));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Seleccione el color de la moto:");
        VisualizarMoto2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 260, 30));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Ingrese el tipo de moto:");
        VisualizarMoto2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        comboBoxTipoMoto2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SemiAutomatica", "Boxer", "SemiDeportiva", "Deportiva", "Chopper", "Naked", "SuperSport", "Scooter" }));
        VisualizarMoto2.add(comboBoxTipoMoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 170, 30));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Marca:");
        VisualizarMoto2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, -1));

        jPanel8.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        VisualizarMoto2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 30, 30));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        VisualizarMoto2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 30, 30));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        VisualizarMoto2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 30, 30));

        jPanel11.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        VisualizarMoto2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 30, 30));

        MarcaMotos.setText("Matca");
        VisualizarMoto2.add(MarcaMotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 176, 140, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Añadir");
        VisualizarMoto2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        AñadirMoto.add(VisualizarMoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 660));

        ModificarInfoAdmin.addTab("tab5", AñadirMoto);

        EliminarMoto.setBackground(new java.awt.Color(255, 255, 255));
        EliminarMoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMotos.setBackground(new java.awt.Color(246, 246, 246));
        tablaMotos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaMotos.setForeground(new java.awt.Color(246, 246, 246));

        tablaDeCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Modelo", "Marca", "Tipo motor", "Cilindraje", "Precio", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDeCarrito.setComponentPopupMenu(jPopupMenu1);
        tablaDeCarrito.setRowHeight(25);
        tablaDeCarrito.setSelectionBackground(new java.awt.Color(51, 0, 0));
        tablaDeCarrito.setShowVerticalLines(true);
        tablaMotos.setViewportView(tablaDeCarrito);

        EliminarMoto.add(tablaMotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1090, 570));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Seleccione la moto que desea eliminar y dé click derecho para borrarla. ");
        EliminarMoto.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 50));

        ModificarInfoAdmin.addTab("tab6", EliminarMoto);

        ModificarMoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ModificarInfoAdmin.addTab("tab7", ModificarMoto);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ModificarInfoAdmin.addTab("tab9", jPanel2);

        verInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ModificarInfoAdmin.addTab("tab10", verInfo);

        VisualizarMoto1.setBackground(new java.awt.Color(255, 255, 255));
        VisualizarMoto1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PARA AÑADIR UNA NUEVA MOTO INGRESE LOS DETALLES QUE SE LE PIDEN A CONTINUACIÓN:");
        VisualizarMoto1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -10, -1, 80));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Seleccione el color de la moto:");
        VisualizarMoto1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 20));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ingrese el tipo de moto:");
        VisualizarMoto1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 20));

        comboBoxTipoMoto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SemiAutomatica", "Boxer", "SemiDeportiva", "Deportiva", "Chopper", "Naked", "SuperSport", "Scooter" }));
        VisualizarMoto1.add(comboBoxTipoMoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 170, 30));

        jPanel7.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        VisualizarMoto1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 20, 20));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        VisualizarMoto1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 20, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        VisualizarMoto1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 20, 20));

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.setForeground(new java.awt.Color(51, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        VisualizarMoto1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 20, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Marca:");
        VisualizarMoto1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        ModificarInfoAdmin.addTab("tab8", VisualizarMoto1);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-circle-34.png"))); // NOI18N
        jPanel15.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 40, 50));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Ingrese el primer nombre:");
        jPanel15.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));

        Nombre1Field1.setForeground(new java.awt.Color(0, 0, 0));
        Nombre1Field1.setBorder(null);
        Nombre1Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre1Field1ActionPerformed(evt);
            }
        });
        jPanel15.add(Nombre1Field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 350, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 350, 20));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Ingrese el segundo nombre:");
        jPanel15.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 20));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-circle-34.png"))); // NOI18N
        jPanel15.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 40, 50));

        Nombre2Field1.setForeground(new java.awt.Color(0, 0, 0));
        Nombre2Field1.setBorder(null);
        Nombre2Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre2Field1ActionPerformed(evt);
            }
        });
        jPanel15.add(Nombre2Field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 350, 30));

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 350, 20));

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Ingrese el primer apellido:");
        jPanel15.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 20));

        Apellido1Field1.setForeground(new java.awt.Color(0, 0, 0));
        Apellido1Field1.setBorder(null);
        Apellido1Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido1Field1ActionPerformed(evt);
            }
        });
        jPanel15.add(Apellido1Field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 350, 30));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-circle-34.png"))); // NOI18N
        jPanel15.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 40, 50));

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 350, 20));

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Ingrese el segundo apellido:");
        jPanel15.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 20));

        Apellido2Field1.setForeground(new java.awt.Color(0, 0, 0));
        Apellido2Field1.setBorder(null);
        Apellido2Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido2Field1ActionPerformed(evt);
            }
        });
        jPanel15.add(Apellido2Field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 350, 30));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-circle-34.png"))); // NOI18N
        jPanel15.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 40, 50));

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 340, 20));

        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Ingrese el correo:");
        jPanel15.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 20));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-email-34 (1).png"))); // NOI18N
        jPanel15.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 40, 50));

        CorreoField1.setForeground(new java.awt.Color(0, 0, 0));
        CorreoField1.setBorder(null);
        CorreoField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoField1ActionPerformed(evt);
            }
        });
        jPanel15.add(CorreoField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 350, 30));

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 350, 20));

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Ingrese la cedula:");
        jPanel15.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-id-42.png"))); // NOI18N
        jPanel15.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 40, 50));

        cedulaField3.setForeground(new java.awt.Color(0, 0, 0));
        cedulaField3.setBorder(null);
        cedulaField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaField3ActionPerformed(evt);
            }
        });
        jPanel15.add(cedulaField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 350, 30));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 350, 20));

        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Ingrese el número telefonico:");
        jPanel15.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel45.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("LOS CAMPOS QUE PERMANEZCAN IGUAL NO SERÁN MODIFICADOS.");
        jPanel15.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-telephone-32.png"))); // NOI18N
        jPanel15.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 40, 50));

        cedulaField4.setForeground(new java.awt.Color(0, 0, 0));
        cedulaField4.setBorder(null);
        cedulaField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaField4ActionPerformed(evt);
            }
        });
        jPanel15.add(cedulaField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 350, 30));

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 350, 20));

        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Ingrese la edad:");
        jPanel15.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 466, -1, 20));

        cedulaField5.setForeground(new java.awt.Color(0, 0, 0));
        cedulaField5.setBorder(null);
        cedulaField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaField5ActionPerformed(evt);
            }
        });
        jPanel15.add(cedulaField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 350, 30));

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 350, 20));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-age-32.png"))); // NOI18N
        jPanel15.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 40, 50));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unnamed-removebg-preview.png"))); // NOI18N
        jLabel49.setText("jLabel28");
        jPanel15.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 440, 350));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("VOLTRIX S.A.S COMPANY SOLO MANEJA CONTRATO A TERMINO INDEFINIDO, SEGÚN LA LEY 2395 DEL 2025");
        jPanel15.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 390, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, -1, -1));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 660));

        ModificarInfoAdmin.addTab("tab11", jPanel13);

        jPanel1.add(ModificarInfoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1140, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1140, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nombre1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre1FieldActionPerformed
        //boton ya creado. agrega el codigo justamente necesario aqui
    }//GEN-LAST:event_Nombre1FieldActionPerformed

    private void Nombre2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre2FieldActionPerformed

    private void Apellido1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido1FieldActionPerformed

    private void Apellido2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido2FieldActionPerformed

    private void CorreoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoFieldActionPerformed

    private void cedulaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaFieldActionPerformed

    private void cedulaField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaField1ActionPerformed

    private void cedulaField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaField2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        ModificarInfoAdmin.setSelectedComponent(jPanel13);
    }//GEN-LAST:event_modificarActionPerformed

    private void Nombre1Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre1Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre1Field1ActionPerformed

    private void Nombre2Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre2Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre2Field1ActionPerformed

    private void Apellido1Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido1Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido1Field1ActionPerformed

    private void Apellido2Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido2Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido2Field1ActionPerformed

    private void CorreoField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoField1ActionPerformed

    private void cedulaField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaField3ActionPerformed

    private void cedulaField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaField4ActionPerformed

    private void cedulaField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido1Field;
    private javax.swing.JTextField Apellido1Field1;
    private javax.swing.JTextField Apellido2Field;
    private javax.swing.JTextField Apellido2Field1;
    private javax.swing.JPanel AñadirMoto;
    private javax.swing.JTextField CorreoField;
    private javax.swing.JTextField CorreoField1;
    private javax.swing.JMenuItem Despedir;
    private javax.swing.JPanel EliminarEmpleado;
    private javax.swing.JPanel EliminarMoto;
    private javax.swing.JTextField MarcaMotos;
    private javax.swing.JPanel ModificarEmpleado;
    private javax.swing.JTabbedPane ModificarInfoAdmin;
    private javax.swing.JPanel ModificarMoto;
    private javax.swing.JMenuItem MotoEliminar;
    private javax.swing.JTextField Nombre1Field;
    private javax.swing.JTextField Nombre1Field1;
    private javax.swing.JTextField Nombre2Field;
    private javax.swing.JTextField Nombre2Field1;
    private javax.swing.JPanel VisualizarEmpleado;
    private javax.swing.JPanel VisualizarMoto1;
    private javax.swing.JPanel VisualizarMoto2;
    private javax.swing.JPanel añadirEmpleado;
    private javax.swing.JTextField cedulaField;
    private javax.swing.JTextField cedulaField1;
    private javax.swing.JTextField cedulaField2;
    private javax.swing.JTextField cedulaField3;
    private javax.swing.JTextField cedulaField4;
    private javax.swing.JTextField cedulaField5;
    private javax.swing.JComboBox<String> comboBoxTipoMoto1;
    private javax.swing.JComboBox<String> comboBoxTipoMoto2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JTable tablaDeCarrito;
    private javax.swing.JTable tablaModificación;
    private javax.swing.JScrollPane tablaMotos;
    private javax.swing.JPanel verInfo;
    private javax.swing.JTable visualizarEmpleados;
    // End of variables declaration//GEN-END:variables
}
