/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Entities.Usuario;
import Controller.UsuarioController;
import Model.Entities.Usuario;
import javax.swing.JOptionPane;

import VisualHelpers.textoSombra;

/**
 *
 * @author gameV
 */
public class Registro extends javax.swing.JFrame {

    private final UsuarioController usuarioController = new UsuarioController();

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        textoSombra correo = new textoSombra("Ingrese su correo aquí.", CorreoField);
        textoSombra contraseña = new textoSombra("Ingrese su contraseña aquí. ", jPasswordField1);
        textoSombra nombre = new textoSombra("Ingrese su nombre primer nombre aquí.", Nombre1Field);
        textoSombra nombre2 = new textoSombra("Ingrese su segundo nombre aquí.", Nombre2Field);
        textoSombra apellido = new textoSombra("Ingrese su primer apellido aquí.", Apellido1Field);
        textoSombra apellido2 = new textoSombra("Ingrese su segundo apellido aquí. ", Apellido2Field);
    }

    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Nombre1Field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Apellido1Field = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Nombre2Field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        Apellido2Field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        CorreoField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cedulaField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/648538-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 550, 440));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 55)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VOLTRIX ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 80));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Moto");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 20));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Registrate y haz parte de la mejor agencia de motos.");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 490, 140));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 350, 20));

        Nombre1Field.setBackground(new java.awt.Color(0, 0, 0));
        Nombre1Field.setForeground(new java.awt.Color(255, 255, 255));
        Nombre1Field.setBorder(null);
        Nombre1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre1FieldActionPerformed(evt);
            }
        });
        jPanel2.add(Nombre1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 350, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-password-24.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 50, 50));

        jPasswordField1.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 300, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 350, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-mail-24.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 190, 40));

        Apellido1Field.setBackground(new java.awt.Color(0, 0, 0));
        Apellido1Field.setForeground(new java.awt.Color(255, 255, 255));
        Apellido1Field.setBorder(null);
        Apellido1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido1FieldActionPerformed(evt);
            }
        });
        jPanel2.add(Apellido1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 350, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 350, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-mail-24.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 50, 40));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 350, 20));

        Nombre2Field.setBackground(new java.awt.Color(0, 0, 0));
        Nombre2Field.setForeground(new java.awt.Color(255, 255, 255));
        Nombre2Field.setBorder(null);
        Nombre2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre2FieldActionPerformed(evt);
            }
        });
        jPanel2.add(Nombre2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 350, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-mail-24.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 50, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-mail-24.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 50, 40));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 350, 20));

        Apellido2Field.setBackground(new java.awt.Color(0, 0, 0));
        Apellido2Field.setForeground(new java.awt.Color(255, 255, 255));
        Apellido2Field.setBorder(null);
        Apellido2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido2FieldActionPerformed(evt);
            }
        });
        jPanel2.add(Apellido2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 350, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-mail-24.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 50, 40));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 350, 20));

        CorreoField.setBackground(new java.awt.Color(0, 0, 0));
        CorreoField.setForeground(new java.awt.Color(255, 255, 255));
        CorreoField.setBorder(null);
        CorreoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoFieldActionPerformed(evt);
            }
        });
        jPanel2.add(CorreoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 350, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-mail-24.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 50, 40));

        cedulaField.setBackground(new java.awt.Color(0, 0, 0));
        cedulaField.setForeground(new java.awt.Color(255, 255, 255));
        cedulaField.setBorder(null);
        cedulaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaFieldActionPerformed(evt);
            }
        });
        jPanel2.add(cedulaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 350, 30));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 350, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 470, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nombre1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre1FieldActionPerformed
        //boton ya creado. agrega el codigo justamente necesario aqui
    }//GEN-LAST:event_Nombre1FieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Extraer los datos de los campos de la interfaz
        String primerNombre = Nombre1Field.getText();
        String segundoNombre = Nombre2Field.getText();
        String primerApellido = Apellido1Field.getText();
        String segundoApellido = Apellido2Field.getText();
        String cedula = cedulaField.getText();
        String email = CorreoField.getText();
        String password = new String(jPasswordField1.getPassword());

        // 2. Crear el objeto Usuario (sin teléfono)
        Usuario nuevoUsuario = new Usuario(
                primerNombre, segundoNombre, primerApellido, segundoApellido,
                cedula, email, password
        );

        // 3. Llamar al Controller
        String resultadoRegistro = usuarioController.registrarUsuario(nuevoUsuario);

        // 4. Manejar la respuesta
        if (resultadoRegistro.equals("OK")) {
            JOptionPane.showMessageDialog(this, "Registro exitoso. ¡Bienvenido!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            // Aquí puedes agregar la lógica para abrir el login
        } else {
            // Muestra el mensaje de error EXACTO que viene del Controller
            // Ejemplo: "Error: El campo Primer Nombre está vacío."
            JOptionPane.showMessageDialog(this, resultadoRegistro, "Error de Validación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Apellido1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido1FieldActionPerformed

    private void Nombre2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre2FieldActionPerformed

    private void Apellido2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido2FieldActionPerformed

    private void CorreoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoFieldActionPerformed

    private void cedulaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido1Field;
    private javax.swing.JTextField Apellido2Field;
    private javax.swing.JTextField CorreoField;
    private javax.swing.JTextField Nombre1Field;
    private javax.swing.JTextField Nombre2Field;
    private javax.swing.JTextField cedulaField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
